(define (sqrt x)
  (define (square guess)
    (* guess guess))
  (define (good-enough? guess x)
    (< (abs (- (square guess) x)) 0.001))
  (define (average guess x)
    (/ (+ guess x) 2))
  (define (improve guess x)
    (average guess (/ x guess)))
  (define (sqrt-iter guess x)
    (if (good-enough? guess x)
	guess
	(sqrt-iter (improve guess x) x)))
    (sqrt-iter 1.0 x))

(sqrt 4)
